timezone = "Europe/London"

[discord]
guild_id = 1234567890

[ferry]
api_url = "https://example.com/api/v1/"
api_key = "abc"
channel_id = 1234567890
banned_word = "train"
emoji_reacts = "ğŸš‚ğŸ˜ ğŸš‡"

[pub]
weekday = 3  # Thursday
hour = 20
channel_id = 1234567890
description = "Casual chat and food. All welcome."